# Generated by Django 4.1.2 on 2022-11-17 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['-created'], 'verbose_name': 'Fruto', 'verbose_name_plural': 'Frutos'},
        ),
    ]
