# Generated by Django 4.1.2 on 2022-11-17 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_producto_created_alter_producto_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='name',
            new_name='nombre',
        ),
    ]
